# Generated by Django 5.2.8 on 2025-11-29 14:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place",
                    models.CharField(
                        help_text="Место, в котором необходимо выполнять привычку.",
                        max_length=255,
                        verbose_name="Место",
                    ),
                ),
                (
                    "time",
                    models.TimeField(
                        help_text="Время, когда необходимо выполнять привычку.",
                        verbose_name="Время",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Формулировка действия, которое представляет собой привычка.",
                        max_length=255,
                        verbose_name="Действие",
                    ),
                ),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False,
                        help_text="Отметьте, если привычка является приятной (вознаграждение), а не полезной.",
                        verbose_name="Приятная привычка",
                    ),
                ),
                (
                    "periodicity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Периодичность выполнения привычки в днях. От 1 до 7.",
                        validators=[
                            django.core.validators.MinValueValidator(
                                1,
                                message="Нельзя выполнять привычку реже, чем 1 раз в 7 дней.",
                            ),
                            django.core.validators.MaxValueValidator(
                                7,
                                message="Нельзя выполнять привычку реже, чем 1 раз в 7 дней.",
                            ),
                        ],
                        verbose_name="Периодичность (дни)",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        blank=True,
                        help_text="Чем вы вознаграждаете себя после выполнения привычки.",
                        max_length=255,
                        null=True,
                        verbose_name="Вознаграждение",
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveSmallIntegerField(
                        help_text="Предполагаемое время на выполнение привычки в секундах (не более 120).",
                        validators=[
                            django.core.validators.MaxValueValidator(
                                120,
                                message="Время на выполнение привычки не может превышать 120 секунд.",
                            )
                        ],
                        verbose_name="Время на выполнение (секунды)",
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False,
                        help_text="Если отмечено, привычка доступна другим пользователям как пример.",
                        verbose_name="Публичная привычка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Создана"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Обновлена"),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        help_text="Приятная привычка, которая выполняется как вознаграждение за эту полезную привычку.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reward_for",
                        to="habits.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Пользователь, создавший привычку.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ("time", "place"),
            },
        ),
    ]
